// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc-bmKfMwL7CclRkyvMrvzNCqpFpOvOpA',
    appId: '1:826815952995:web:74a4252e83cc84a3ebe056',
    messagingSenderId: '826815952995',
    projectId: 'mealprep2135',
    authDomain: 'mealprep2135.firebaseapp.com',
    storageBucket: 'mealprep2135.appspot.com',
    measurementId: 'G-6GCC6PL6ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqB1DHcKf7KHVe4tJsAySjsnSBMtOUrPA',
    appId: '1:826815952995:android:d69133e2df7794f4ebe056',
    messagingSenderId: '826815952995',
    projectId: 'mealprep2135',
    storageBucket: 'mealprep2135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnbN1V4bd8LQO3LQ6sZlGQNutP-IxGlJ0',
    appId: '1:826815952995:ios:7b2eb2a94621d11bebe056',
    messagingSenderId: '826815952995',
    projectId: 'mealprep2135',
    storageBucket: 'mealprep2135.appspot.com',
    iosBundleId: 'com.yaklabs.mealPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnbN1V4bd8LQO3LQ6sZlGQNutP-IxGlJ0',
    appId: '1:826815952995:ios:797f6d15f8fec86eebe056',
    messagingSenderId: '826815952995',
    projectId: 'mealprep2135',
    storageBucket: 'mealprep2135.appspot.com',
    iosBundleId: 'com.example.mealPrep.RunnerTests',
  );
}
